apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docmag.fullname" . }}
  labels:
    app: {{ template "docmag.name" . }}
    chart: {{ template "docmag.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.properties: |
    document.pagesize=5
    tagging.threshold=0.88
