version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch01
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docmag-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      #TODO Shut these ports down for non-development scenarios
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: kibana
    depends_on: [ elasticsearch ]
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  fscrawler:
    build: fscrawler/.
    container_name: fscrawler
    depends_on: [ elasticsearch ]
    #FIXME See Docker Compose Issue #3140
    entrypoint: ./bin/launch_wait.sh elasticsearch01 9200
    command: ./bin/fscrawler --config_dir /etc/fscrawler scanned --rest
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/fscrawler/docs:ro
      - fscconfig:/etc/fscrawler
    networks:
      - esnet

  docmagui:
    build: .
    image: docmag/docmagui
    container_name: docmagui
    environment:
      - ELASTICSEARCH_HOST=elasticsearch01
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTER=docmag-cluster
      - DOCUMENT_ROOT=/usr/share/docmagui/docs
    depends_on: [ elasticsearch ]
    ports:
      - 1080:8080
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/docmagui/docs:ro
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  fscconfig:
    driver: local

networks:
  esnet:
