version: '3'
services:
  elasticsearch:
    ports:
      - 9300:9300
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: kibana
    depends_on: [ elasticsearch ]
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  fscrawler:
    build: fscrawler/.
    ports:
      - 3080:8080

  docmagui:
    build: .
    ports:
      - 2080:8080
