version: '3'
services:
  elasticsearch:
    image: deckerego/elasticsearch:5.6.4
    container_name: elasticsearch01
    environment:
      - "ES_JAVA_OPTS=-Xms800M -Xmx800M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - esnet

  docidx:
    image: deckerego/docidx:0.4.5
    container_name: docidx
    depends_on: [ elasticsearch ]
    environment:
      - "FS_JAVA_OPTS=-Xms512m -Xmx1g"
      - CRAWLER_ROOTPATH=/usr/share/docidx/docs
      - ELASTICSEARCH_HOST=elasticsearch01
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTER=docmag-cluster
      - ELASTICSEARCH_BATCHSIZE=10
      - ELASTICSEARCH_BATCHWAITMILLIS=10000
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/docidx/docs:ro
    networks:
      - esnet

  docmagui:
    image: deckerego/docmagui:0.4.5
    container_name: docmagui
    environment:
      - ELASTICSEARCH_HOST=elasticsearch01
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTER=docmag-cluster
      - DOCUMENT_ROOT=/usr/share/docmagui/docs
      - AUTH_USERNAME=docmag
      - AUTH_PASSWORD=supersecretpassword
    depends_on: [ elasticsearch ]
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/docmagui/docs:ro
    networks:
      - esnet

  modsecurity:
    image: deckerego/modsecurity-crs:latest
    container_name: modsecurity
    environment:
      - PARANOIA=3
    depends_on: [ docmagui ]
    ports:
      - 1080:80
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  fscconfig:
    driver: local

networks:
  esnet:
