version: '3'
services:
  elasticsearch:
    image: deckerego/elasticsearch:5.6.4
    container_name: elasticsearch01
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docmag-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms800M -Xmx800M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - esnet

  docidx:
    image: deckerego/docidx
    container_name: docidx
    depends_on: [ elasticsearch ]
    environment:
      - "FS_JAVA_OPTS=-Xms2g -Xmx4g"
      - CRAWLER_ROOTPATH=/usr/share/docidx/docs
      - ELASTICSEARCH_HOST=elasticsearch01
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTER=docmag-cluster
      - ELASTICSEARCH_BATCHSIZE=10
      - ELASTICSEARCH_BATCHWAITMILLIS=10000
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/docidx/docs:ro
    networks:
      - esnet

  docmagui:
    image: deckerego/docmagui
    container_name: docmagui
    environment:
      - ELASTICSEARCH_HOST=elasticsearch01
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTER=docmag-cluster
      - DOCUMENT_ROOT=/usr/share/docmagui/docs
    depends_on: [ elasticsearch ]
    volumes:
      - ${DOCUMENT_HOST_DIR}:/usr/share/docmagui/docs:ro
    networks:
      - esnet

  modsecurity:
    build: modsecurity/.
    container_name: modsecurity
    environment:
      - PARANOIA=3
    depends_on: [ docmagui ]
    ports:
      - 1080:80
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  fscconfig:
    driver: local

networks:
  esnet:
