version: '2'
services:
  elasticsearch:
    build: es/.
    container_name: elasticsearch01
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: kibana
    depends_on: [ elasticsearch ]
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
