replicaCount: 1

image:
  repository: deckerego/docmagui
  tag: 0.4.9
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"

volumes:
  document:
    storage: 400Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - docmag.yourcluster.egg
  tls:
    secretName: docmag-tls

nodeSelector: {}

tolerations: []

affinity: {}
