apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: docmagui-scanneddoc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
