apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: elasticsearch
  revisionHistoryLimit: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: elasticsearch
    spec:
      containers:
      - name: elasticsearch01
        image: deckerego/elasticsearch:5.6.4
        env:
        - name: ES_JAVA_OPTS
          value: -Xms800M -Xmx800M
        - name: bootstrap.memory_lock
          value: "false"
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
        ports:
          - containerPort: 9300
            name: transport
            protocol: TCP
          - containerPort: 9200
            name: http
            protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata01
      restartPolicy: Always
      volumes:
      - name: esdata01
        persistentVolumeClaim:
          claimName: esdata01
status: {}
