apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jellis/bin/kompose -f ../docker-compose.yml -f ../docker-compose-devel.yml
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms800M -Xmx800M
        image: deckerego/elasticsearch:5.6.4
        name: elasticsearch01
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata01
      restartPolicy: Always
      volumes:
      - name: esdata01
        persistentVolumeClaim:
          claimName: esdata01
status: {}
