apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: transport
    port: 9300
  - name: http
    port: 9200
  selector:
    service: elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      containers:
      - name: elasticsearch01
        image: deckerego/elasticsearch:5.6.4
        env:
        - name: ES_JAVA_OPTS
          value: -Xms800M -Xmx800M
        - name: bootstrap.memory_lock
          value: "false"
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
        ports:
          - containerPort: 9300
            name: transport
            protocol: TCP
          - containerPort: 9200
            name: http
            protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata01
      volumes:
      - name: esdata01
        persistentVolumeClaim:
          claimName: esdata01
