apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: transport
    port: 9300
  - name: http
    port: 9200
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
