apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/jellis/bin/kompose -f ../docker-compose.yml -f ../docker-compose-devel.yml
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
