apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: esdata01
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
      server: visor.deckerego.net
      path: "/home/docmag/esdata01"
