apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  ports:
  - name: http
    port: 5601
  selector:
    io.kompose.service: kibana
  externalIPs:
  - 192.168.129.206
status:
  loadBalancer: {}
