apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.6.4
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
        ports:
          - containerPort: 5601
            name: http
            protocol: TCP
      restartPolicy: Always
status: {}
