apiVersion: v1
kind: Service
metadata:
  name: modsecurity
spec:
  ports:
  - name: http
    port: 80
  selector:
    service: modsecurity
  externalIPs:
  - 127.0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modsecurity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: modsecurity
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        service: modsecurity
    spec:
      containers:
      - env:
        - name: PARANOIA
          value: "3"
        image: deckerego/modsecurity-crs:latest
        name: modsecurity
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
