apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: modsecurity
  name: modsecurity
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: modsecurity
    spec:
      containers:
      - env:
        - name: PARANOIA
          value: "3"
        image: deckerego/modsecurity-crs:latest
        name: modsecurity
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Always
status: {}
