apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jellis/bin/kompose convert -f ../docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: modsecurity
  name: modsecurity
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: modsecurity
    spec:
      containers:
      - env:
        - name: PARANOIA
          value: "3"
        image: deckerego/modsecurity-crs:latest
        name: modsecurity
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
