replicaCount: 1

image:
  repository: deckerego/modsecurity-crs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalIP: 127.0.0.1

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
