apiVersion: v1
kind: Service
metadata:
  name: {{ template "modsecurity.fullname" . }}
  labels:
    app: {{ template "modsecurity.name" . }}
    chart: {{ template "modsecurity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: http
  externalIPs:
  - {{ .Values.service.externalIP }}
  selector:
    app: {{ template "modsecurity.name" . }}
    release: {{ .Release.Name }}
